INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Indian');
INSERT INTO category (description) VALUES ('Chinese');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Ounce');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Each');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Dash');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Pint');