version: '3'         # version of docker-compose 
services:
  monodb:            # Container Name
    image: mongo     # The image
    ports:
      - 27017:27017
    environment:     # the environment variables
      - Mongo_INITDB_ROOT_USERNAME=admin
      - Mongo_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8080
    environment:     # the environment variables
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  